services:
  postgres:
    container_name: postgres
    image: postgres:15.1-alpine
    restart: always
    ports:
      - 5409:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: finance-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
